name: Rust

on:
  push:
    branches: [ main, rewrite ]
  pull_request:
    branches: [ main ]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install deps
      run: sudo apt update && sudo apt install libopenimageio-dev libglfw3-dev

    - name: Run tests
      run: cargo test --verbose --features window
  macos:
    runs-on: macos-latest
    env:
      HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1
    steps:
    - uses: actions/checkout@v2
    - run: brew update

    - name: Install python
      run: brew install --force --overwrite python@3.11 || brew link --force python@3.11

    - name: Install deps
      run: brew install --force --overwrite openimageio glfw

    - name: Run tests
      run: cargo test --verbose --features window
  linux_nightly:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install deps
      run: sudo apt update && sudo apt install libopenimageio-dev libglfw3-dev

    - name: Nightly
      run: rustup toolchain install nightly

    - name: Run tests
      run: cargo +nightly test --verbose --features window
  macos_nightly:
    runs-on: macos-latest
    env:
      HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1
    steps:
    - uses: actions/checkout@v2
    - run: brew update

    - name: Install python
      run: brew install --force --overwrite python@3.11 || brew link --force python@3.11

    - name: Install deps
      run: brew install --force --overwrite openimageio glfw

    - name: Nightly
      run: rustup toolchain install nightly

    - name: Run tests
      run: cargo +nightly test --verbose --features window
  linux_no_default_features:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install deps
      run: sudo apt update && sudo apt install libopenimageio-dev libglfw3-dev

    - name: Run tests
      run: cargo test --no-default-features --features=magick --verbose
  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install deps
      run: sudo apt update && sudo apt install libopenimageio-dev libglfw3-dev

    - name: Nightly
      run: rustup toolchain install nightly --profile=default

    - name: Run tests
      run: cargo +nightly clippy --features window


